onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /scouting_test_tb/lhc_clk
add wave -noupdate /scouting_test_tb/dut/clk240
add wave -noupdate /scouting_test_tb/cntr_rst
add wave -noupdate /scouting_test_tb/oc0
add wave -noupdate /scouting_test_tb/start
add wave -noupdate /scouting_test_tb/ec0
add wave -noupdate /scouting_test_tb/bcres
add wave -noupdate /scouting_test_tb/tcm_inst/bx_nr
add wave -noupdate /scouting_test_tb/tcm_inst/orbit_nr
add wave -noupdate /scouting_test_tb/dut/lane_out
add wave -noupdate /scouting_test_tb/dut/lhc_rst
add wave -noupdate /scouting_test_tb/dut/ctrs
add wave -noupdate /scouting_test_tb/dut/valid_lo
add wave -noupdate /scouting_test_tb/dut/valid_hi
add wave -noupdate /scouting_test_tb/dut/start
add wave -noupdate /scouting_test_tb/dut/strobe
add wave -noupdate /scouting_test_tb/dut/sValid
add wave -noupdate /scouting_test_tb/dut/s_in0_mux0
add wave -noupdate /scouting_test_tb/dut/s_in0_mux1
add wave -noupdate /scouting_test_tb/dut/s_in0_mux2
add wave -noupdate /scouting_test_tb/dut/s_in0_mux3
add wave -noupdate /scouting_test_tb/dut/s_in0_mux4
add wave -noupdate /scouting_test_tb/dut/s_in0_mux5
add wave -noupdate /scouting_test_tb/dut/s_in0_mux6
add wave -noupdate /scouting_test_tb/dut/s_in0_mux7
add wave -noupdate /scouting_test_tb/dut/s_in0_mux8
add wave -noupdate /scouting_test_tb/dut/s_in0_mux9
add wave -noupdate /scouting_test_tb/dut/s_in1_mux0
add wave -noupdate /scouting_test_tb/dut/s_in1_mux1
add wave -noupdate /scouting_test_tb/dut/s_in1_mux2
add wave -noupdate /scouting_test_tb/dut/s_in1_mux3
add wave -noupdate /scouting_test_tb/dut/s_in1_mux4
add wave -noupdate /scouting_test_tb/dut/s_in1_mux5
add wave -noupdate /scouting_test_tb/dut/s_in1_mux6
add wave -noupdate /scouting_test_tb/dut/s_in1_mux7
add wave -noupdate /scouting_test_tb/dut/s_in1_mux8
add wave -noupdate /scouting_test_tb/dut/s_in1_mux9
add wave -noupdate /scouting_test_tb/dut/s_in2_mux0
add wave -noupdate /scouting_test_tb/dut/s_in2_mux1
add wave -noupdate /scouting_test_tb/dut/s_in2_mux2
add wave -noupdate /scouting_test_tb/dut/s_in2_mux3
add wave -noupdate /scouting_test_tb/dut/s_in2_mux4
add wave -noupdate /scouting_test_tb/dut/s_in2_mux5
add wave -noupdate /scouting_test_tb/dut/s_in2_mux6
add wave -noupdate /scouting_test_tb/dut/s_in2_mux7
add wave -noupdate /scouting_test_tb/dut/s_in2_mux8
add wave -noupdate /scouting_test_tb/dut/s_in2_mux9
add wave -noupdate /scouting_test_tb/dut/s_in3_mux0
add wave -noupdate /scouting_test_tb/dut/s_in3_mux1
add wave -noupdate /scouting_test_tb/dut/s_in3_mux2
add wave -noupdate /scouting_test_tb/dut/s_in3_mux3
add wave -noupdate /scouting_test_tb/dut/s_in3_mux4
add wave -noupdate /scouting_test_tb/dut/s_in3_mux5
add wave -noupdate /scouting_test_tb/dut/s_in3_mux6
add wave -noupdate /scouting_test_tb/dut/s_in3_mux7
add wave -noupdate /scouting_test_tb/dut/s_in3_mux8
add wave -noupdate /scouting_test_tb/dut/s_in3_mux9
add wave -noupdate /scouting_test_tb/dut/s_in4_mux0
add wave -noupdate /scouting_test_tb/dut/s_in4_mux1
add wave -noupdate /scouting_test_tb/dut/s_in4_mux2
add wave -noupdate /scouting_test_tb/dut/s_in4_mux3
add wave -noupdate /scouting_test_tb/dut/s_in4_mux4
add wave -noupdate /scouting_test_tb/dut/s_in4_mux5
add wave -noupdate /scouting_test_tb/dut/s_in4_mux6
add wave -noupdate /scouting_test_tb/dut/s_in4_mux7
add wave -noupdate /scouting_test_tb/dut/s_in4_mux8
add wave -noupdate /scouting_test_tb/dut/s_in4_mux9
add wave -noupdate /scouting_test_tb/dut/s_in5_mux0
add wave -noupdate /scouting_test_tb/dut/s_in5_mux1
add wave -noupdate /scouting_test_tb/dut/s_in5_mux3
add wave -noupdate /scouting_test_tb/dut/s_in5_mux4
add wave -noupdate /scouting_test_tb/dut/s_in5_mux6
add wave -noupdate /scouting_test_tb/dut/s_in5_mux7
add wave -noupdate /scouting_test_tb/dut/s_in5_mux8
add wave -noupdate /scouting_test_tb/dut/s_in5_mux9
add wave -noupdate /scouting_test_tb/dut/s_in5_mux5
add wave -noupdate /scouting_test_tb/dut/s_in5_mux2
add wave -noupdate /scouting_test_tb/dut/mux0_i/s_out
add wave -noupdate /scouting_test_tb/dut/mux0_i/frame_cntr
add wave -noupdate /scouting_test_tb/dut/mux0_i/clk
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {101795 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 329
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {88304916 ps} {90642964 ps}
